### ISSUE TITLE
Simulated Underwater Embodied Intelligence

### ISSUE THREAD

**Issue by CoderXuans** [zjunlp/OceanGPT#3]
@coderxyd 
Hello, I am conducting research related to planning for underwater robots such as AUVs and semi-submersibles. Your introduction mentioned evaluating OceanGPT's preliminary capabilities for underwater robot control, including tasks like trajectory planning within simulators. Could you provide a detailed explanation of how this is achieved in RViz?

**Comment by zxlzr** [comment]
Hi, thank you for your interest in our work.

We tried two approaches:

1. Feed the simulator's execution code (input operations output as code) to GPT-4 and write several prompts to generate hundreds of instructions, then fine-tune the model using LoRA. The model can handle several executions seen during training. 

2. Prompt engineering (input operations output as code). The model could handle simple operations, but there were hallucinations with more complex operations.

**Comment by zxlzr** [comment]
Hi, do you have any further issues?

**Comment by CoderXuans** [comment]
Thank you for your quick response. Could you please clarify if the first method used GPT-4? Was the second method based on OceanGPT?

I'm still a bit unclear about the specific steps involved in writing multiple prompts, generating hundreds of instructions, and then fine-tuning the model using LoRA. Could you provide an example? For instance, using a scenario where an underwater vehicle tracks a specific trajectory as input and generates code based on that?
Have you tried integrating with existing autonomous driving frameworks?

**Comment by zxlzr** [comment]
This is actually an example of using OceanGPT to call tools (trained with synthesis data from GPT-4), and the process is as follows:

1 Refer to the documentation to find the API codes for operations within the simulator (there are usually many). Manually create an example of input and output, with the output being the operation API code.

2 Feed the above content to GPT-4 to synthesize multiple instructions.

3 Manually check the results and correct any errors.

4 Train a LoRA model with OceanGPT.

If there are any issues, it is recommended that you refer to relevant papers on LLM tool calling and code generation.

We don't have the funding to try existing autonomous driving frameworks.

**Comment by zxlzr** [comment]
> the second method based on OceanGPT?

 the second method is based on OceanGPT, but the performance is not good compared with the fine-tuning method (method1)

**Comment by CoderXuans** [comment]
Thank you for your reply. Recently, I discovered an open-source closed-loop autonomous driving framework called LMDrive, which requires almost no cost.

**Comment by zxlzr** [comment]
cool, but we are focusing on underwater environment, it's quite different.

**Comment by CoderXuans** [comment]
It seems that current conventional autonomous driving scenarios can at most be applied to the surface of the water.

**Comment by zxlzr** [comment]
> It seems that current conventional autonomous driving scenarios can at most be applied to the surface of the water.

yes, but underwater is quite different.
